{% set name = "hello" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: ../dist/{{ name }}-{{ version }}.tar.gz

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  ignore_run_exports:
    - python

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python {{ python }}
    - pip
    - setuptools
  run:
    - python

about:
  home: http://github.com/chrisjbillington/conda-build-test
  summary: 'Test module for building conda packages'
  license: 'BSD'
  license_file: ../LICENSE
