package:
  name: hello
  version: 0.1.0

source:
  url: ../dist/hello-0.1.0.tar.gz

build:
  script: {{ PYTHON }} -m pip install .
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python
    - pip
    - wheel

  run:
    - python

about:
  home: http://github.com/chrisjbillington/conda-build-test
  summary: 'Test module for building conda packages'
  license: 'BSD'
  license_file: ../LICENSE
