package:
  name: labscript-c-extensions
  version: 1.0.1

source:
  url: https://files.pythonhosted.org/packages/e1/f0/7b2bdebab5b1b16c699caed0a1eb64f794122ce72265b6339c418b07ccec/labscript-c-extensions-1.0.1.tar.gz
  sha256: a57976734a77bd921265ccd6f28d81a92b733339424e2cf29c4b9ff69ab573d7

build:
  script: {{ PYTHON }} -m pip install .
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python
    - pip
    - wheel
    - setuptools
    - wheel
    - setuptools-scm
    - cython

  run:
    - python
    - importlib-metadata
    - setuptools-scm
    - numpy

about:
  home: http://labscriptsuite.org
  summary: 'A module containing C-extensions for the labscript suite'
  license: 'BSD'
  license_file: LICENSE
