name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - { os: macos-13,         python: '3.12',  arch: x64 }
          - { os: macos-13,         python: '3.11',  arch: x64 }

          - { os: ubuntu-latest,    python: '3.12',  arch: x64 }
          - { os: ubuntu-latest,    python: '3.11',  arch: x64 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python }}
          architecture: ${{ matrix.arch }}
          miniconda-version: "latest"
          # auto-activate-base: true
          # activate-environment: ""

      - name: Conda package (Unix)
        shell: bash -l {0}
        run: |
          conda install -c labscript-suite setuptools-conda
          setuptools-conda build --channels conda-forge . 

      - name: Upload Artifact
        if: matrix.conda
        uses: actions/upload-artifact@v4
        with:
          name: conda_packages-${{ matrix.os }}-py${{ matrix.python }}-${{ matrix.arch }}
          path: ./conda_packages
