name: Build and Release

on:
  push:
    branches:
      - master

env:
  # Configuration for a package with compiled extensions:
  PURE: false
  NOARCH: false

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - { os: macos-13,         python: '3.12',  arch: x64, conda: true }
          - { os: macos-13,         python: '3.11',  arch: x64, conda: true }

          - { os: ubuntu-latest,    python: '3.12',  arch: x64, conda: true }
          - { os: ubuntu-latest,    python: '3.11',  arch: x64, conda: true }

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Variables for Conda Build
        if: matrix.conda
        shell: bash
        run: |
          CONDA_BUILD_ARGS=""
          if [ $NOARCH == true ]; then
              CONDA_BUILD_ARGS+= --noarch
          fi
          echo "CONDA_BUILD_ARGS=$CONDA_BUILD_ARGS" >> $GITHUB_ENV

      - name: Use newer conda-forge compiler toolchains on macos
        if: (matrix.conda && runner.os != 'macOS')
        shell: bash
        run: |
          if [ $PURE == false ]; then
              CONDA_BUILD_ARGS+= --channels conda-forge
          fi
          echo "CONDA_BUILD_ARGS=$CONDA_BUILD_ARGS" >> $GITHUB_ENV

      - name: Install Miniconda
        if: matrix.conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python }}
          architecture: ${{ matrix.arch }}
          miniconda-version: "latest"

      - name: Conda package (Unix)
        if: (matrix.conda && runner.os != 'Windows')
        shell: bash -l {0}
        run: |
          conda config --add channels conda-forge
          conda install -c labscript-suite setuptools-conda
          setuptools-conda build $CONDA_BUILD_ARGS .

      - name: Conda Package (Windows)
        if: (matrix.conda && runner.os == 'Windows')
        shell: cmd /C CALL {0}
        run: |
          conda config --add channels conda-forge && ^
          conda install -c labscript-suite setuptools-conda && ^
          setuptools-conda build %CONDA_BUILD_ARGS% --croot ${{ runner.temp }}\cb .

      - name: Upload Artifact
        if: matrix.conda
        uses: actions/upload-artifact@v4
        with:
          name: conda_packages-${{ matrix.os }}-py${{ matrix.python }}-${{ matrix.arch }}
          path: ./conda_packages
