name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true

      - name: Build Conda Package
        shell: cmd /C CALL {0}
        run: |
          pip download git+https://github.com/zephyrproject-rtos/windows-curses/ && ^
          unzip windows-curses-2.2.0.zip && ^
          cd windows-curses && ^
          conda install -c labscript-suite setuptools-conda && ^
          setuptools-conda build --from-downloaded-wheel .
