name: Build

on:
  push:
    branches:
      - master


defaults:
  run:
    shell: bash


jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Conda Package
        shell: cmd
        run: build_conda_package.bat
